### ISSUE TITLE
auto deployment 

### ISSUE THREAD

**Issue by tsinat** [raeprojects/www-raeprojects-org#5] opened 2016-01-13 01:01 UTC
dev.raeprojects.org is failing to deploy automatically.

**Comment by anbestephen** [comment] 2016-01-13 17:50
I am actively working to fix this  problem. you can follow the conversation at this  [issue's](https://github.com/gruntjs/grunt-contrib-imagemin/issues/330#issuecomment-171150584) comments. I have also opened a new [issue](https://github.com/gruntjs/grunt-contrib-imagemin/issues/345) tageting this problem. Fell free to follow or join the conversation.

**Comment by KnownTraveler** [comment] 2016-01-13 17:57
I have successfully moved passed this issue by swapping out "grunt-contrib-imagemin": "^1.0.0" for "grunt-image": "^1.2.1" ... and subsequently updating my Gruntfile.js by replacing imagemin tasks with image tasks.

I've referenced the fix I used in the issue 
https://github.com/gruntjs/grunt-contrib-imagemin/issues/345

**Comment by anbestephen** [comment] 2016-01-13 18:00
the problem is fixed. I am closing this issue now

**Closed as completed by anbestephen** 2016-01-13 18:00 UTC
Labels: bug
